DATA:
 PATH: '/kaggle/input/hyper-kvasir/labeled_images_resize'
 ANNO: '../resource/hyper_kvasir/df_6_pathologies_mock_2_8.csv'
 IMG_SIZE: 112
 BATCH_SIZE: 16
 NUM_WORKERS: 2
 MOCKUP_SSL: True
 MU: 4
 INPUT_NAME: 'image'
 TARGET_NAME: 'target'
 IS_CROP: False
MODEL:
 NUM_CLASSES: 7
 NAME: 'densenet161'
 PRE_TRAIN: True
 PRE_TRAIN_PATH: '/kaggle/input/checkpoint-abnormal/sup_densenet161_abnormal_224.pth'
 MARGIN: None
 TYPE_SEMI: 'FixMatch'
TRAIN:
 IS_SSL: True
 EPOCHS: 150
 BASE_LR: 0.001
 WARMUP_LR: 0.0005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 5  
 DECAY_EPOCHS: 10
 OPT_NAME: 'Adam'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 5
 SCH_NAME: 'step'
 LR_DECAY: 0.8 
 USE_EMA: True
 EMA_DECAY: 0.999
 EVAL_STEP: 256
 CLS_WEIGHT: True
 THRES: 0.95
 T: 1.0
 LAMBDA_U: 1.5
 LAMBDA_C: 1.5
 SAVE_CP: '/kaggle/working/'