DATA:
 PATH: '/kaggle/input/hyper-kvasir/labeled_images_resize'
 ANNO: '../resource/hyper_kvasir/df_6_pathologies_ite_2.csv'
 IMG_SIZE: 224
 BATCH_SIZE: 32
 NUM_WORKERS: 2
 MOCKUP_SSL: False
 MU: 6
 INPUT_NAME: 'image'
 TARGET_NAME: 'target'
 IS_CROP: True
MODEL:
 NUM_CLASSES: 6
 NAME: 'resnet50sasa'
 PRE_TRAIN: True
 PRE_TRAIN_PATH: '/kaggle/input/checkpoint-abnormal/sup_resnet50sasa_abnormal_224.pth'
 MARGIN: None
 TYPE_SEMI: 'FixMatch'
 IS_TRIPLET: False
TRAIN:
 IS_SSL: False
 EPOCHS: 150
 BASE_LR: 0.01
 WARMUP_LR: 0.0005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 5  
 DECAY_EPOCHS: 10
 OPT_NAME: 'SGD'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 5
 SCH_NAME: 'step'
 LR_DECAY: 0.8 
 USE_EMA: True
 EMA_DECAY: 0.999
 EVAL_STEP: 256
 CLS_WEIGHT: True
 THRES: 0.9
 T: 1.0
 LAMBDA_U: 1.
 LAMBDA_C: 4.
 SAVE_CP: '/kaggle/working/'
 MIXUP: 0.
 CUTMIX: 0.
 CUTMIX_MINMAX: None
 MIXUP_PROB: 1.0
 MIXUP_SWITCH_PROB: 0.5
 MIXUP_MODE: 'batch'
 LABEL_SMOOTHING: 0.0