DATA:
 PATH: 'D:\data\endoscopic\hyper_kvasir\labeled_images_deform'
 ANNO: '../resource/hyper_kvasir/full_labeled_group.csv'
 IMG_SIZE: 224
 BATCH_SIZE: 8
 NUM_WORKERS: 0
MODEL:
 NUM_CLASSES: 6
TRAIN:
 EPOCHS: 10
 BASE_LR: 0.001
 WARMUP_LR: 0.0000005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 20  
 OPT_NAME: 'Adam'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 5
 SCH_NAME: 'step'
 USE_EMA: True
 EMA_DECAY: 0.999
 EVAL_STEP: 512