DATA:
 PATH: 'D:\data\endoscopic\hyper_kvasir\labeled_images_deform'
 ANNO: '../resource/hyper_kvasir/full_labeled_group.csv'
 IMG_SIZE: 224
 BATCH_SIZE: 1
 NUM_WORKERS: 0
 MOCKUP_SSL: True
 MOCKUP_SIZE: 0.9
 MU: 7
 INPUT_NAME: 'image'
 TARGET_NAME: 'target'
MODEL:
 NUM_CLASSES: 5
TRAIN:
 IS_SSL: True
 EPOCHS: 10
 BASE_LR: 0.001
 WARMUP_LR: 0.00005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 5  
 DECAY_EPOCHS: 5
 OPT_NAME: 'Adam'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 5
 SCH_NAME: 'step'
 LR_DECAY: 0.8
 USE_EMA: True
 EMA_DECAY: 0.999
 EVAL_STEP: 16
 CLS_WEIGHT: True
 THRES: 0.95
 T: 1.0
 LAMBDA_U: 0.6
 

