DATA:
 PATH: 'D:\data\endoscopic\hyper_kvasir\labeled_images'
 ANNO: '../resource/hyper_kvasir/df_6_pathologies_ite_1.csv'
 IMG_SIZE: 224
 BATCH_SIZE: 32
 NUM_WORKERS: 2
 MOCKUP_SSL: False
 MU: 6
 INPUT_NAME: 'image'
 TARGET_NAME: 'target'
 IS_CROP: True
MODEL:
 NUM_CLASSES: 6
 NAME: 'resnet50'
 PRE_TRAIN: True
 PRE_TRAIN_PATH: 'None'
 MARGIN: None
 IS_TRIPLET: True
TRAIN:
 IS_SSL: False
 EPOCHS: 100
 BASE_LR: 0.001
 WARMUP_LR: 0.0005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 5  
 DECAY_EPOCHS: 5
 OPT_NAME: 'Adam'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 5
 SCH_NAME: 'step'
 LR_DECAY: 0.8 
 USE_EMA: True
 EMA_DECAY: 0.999
 EVAL_STEP: 256
 CLS_WEIGHT: True
 THRES: 0.9
 T: 1.0
 LAMBDA_U: 1.
 LAMBDA_C: 1.
 SAVE_CP: '/kaggle/working/'
 MIXUP: 0.0
 CUTMIX: 0.0
 CUTMIX_MINMAX: None
 MIXUP_PROB: 0.0
 MIXUP_SWITCH_PROB: 0.0
 MIXUP_MODE: 'batch'
 LABEL_SMOOTHING: 0.0